### PR TITLE
Add array type for config

### PR DESCRIPTION
**Pull request by ys**
This will add the possibility to get an array of string to the config

```
ACRONYMS=lol, rofl, trololol
```

```
optional :acronyms, array

#=> ["lol", "rofl", "trololol"]
```

```
optional :random_numbers, array(int)

#=> [1, 2, 3]
```

### CODE REVIEW

**Comment by pedro** [comment]
THIS IS AWESOME.

(fwiw if anyone doesn't quite get it, this is really helpful for things you have to rotate like temporary passwords)

Merging. I noticed this whole area is not tested so will add tests next.

**Comment by ys** [comment]
I wanted to add tests too, but waited for feedback first:)

**Comment by pedro** [comment]
Ah! Go for it then if you want :} didn't start on it or anything.

**Comment by ys** [comment]
Ok will take a closer look tomorrow to test them all:)

**Pull request merged**
