### PR TITLE
Add Serialize helpers

### PR DESCRIPTION
**Pull request by gudmundur**
My take on @ys's serialize helpers. The two of us discussed this out-of-band and this is my understanding of where we should head with this.

This PR supersedes #182.

### CODE REVIEW

**Comment by pedro** [comment]
This looks great to me!

**Comment by brandur** [comment]
+1 from me too!

You may want to consider sanitizing your commits a bit more to represent a slightly cleaner progression towards the implementation, but it's not a big deal.

**Comment by gudmundur** [comment]
This was a nice exercise in rebasing to death. @brandur commits looking better?

**Comment by gudmundur** [comment]
I'm thinking about adding a sanity check that if you call `serialize` without specifying a serializer, it'll blow up with a `500`, similar to what API does for missing permissions, etc. That, and some specs.

**Comment by brandur** [comment]
> This was a nice exercise in rebasing to death. @brandur commits looking better?

Yep! Thanks for cleaning that up.

> I'm thinking about adding a sanity check that if you call serialize without specifying a serializer, it'll blow up with a 500, similar to what API does for missing permissions, etc. That, and some specs.

Nice idea! +1 if you want to try your hand at this. Please include a reasonable error message on failure :)

**Comment by gudmundur** [comment]
@brandur there you go!

**Comment by brandur** [comment]
@gudmundur Awesome! Looks good to me. Let's get this in :)

**Pull request merged**
