### PR TITLE
Add minor refactor to initializer template

### PR DESCRIPTION
**Pull request by DyegoCosta**
[Review on Reviewable](https://reviewable.io/reviews/interagent/pliny/171)

### CODE REVIEW

**Comment by pedro** [comment]
awesome :} thank you!

**Comment by ys** [comment]
Why this change? is it some performance stuff?

As far as I know

```
Array([:lol]) #=> [:lol]
Array(:lol) #=> [:lol]
```

Am I misreading something?

**Comment by pedro** [comment]
Just shorter – the outcome should be the same (you can call `require!('foo')` or `require!(%w( foo ))`).

**Comment by ys** [comment]
Yes, sorry I deleted my comment I misread totally... Red was new in my head... Don't ask why, because I dunno.:P

**Comment by pedro** [comment]
hahaha cool no worries :}

**Pull request merged**
