### PR TITLE
Rename endpoints to resources

### PR DESCRIPTION
**Pull request by pedro**
The first is a bit confusing because each file is actually a
collection of endpoints. I like "resources" because it tells devs
what each file should expose, not to mention it sounds more
familiar to API developers and all.

Thoughts @geemus @mfine @brandur ?

### CODE REVIEW

**Comment by gudmundur** [comment]
@pedro Isn't this a little too late by now? :)

**Comment by dmathieu** [comment]
I agree it's too late to make such a change.
Also, it would need a major release, probably with deprecation warnings first.

**Comment by geemus** [comment]
Could be ok if it supports both, but might indeed end up in some weird cases of people unexpectedly having both directories and finding that confusing.

**Comment by pedro** [comment]
Right on, I still think it's a good chance but don't care enough to want to drive it :} Closing!

Small note on major release though: being still on major version zero we're still allowed breaking changes, at least in theory :}

**Comment by gudmundur** [comment]
@pedro haha :)

**Pull request closed without merging**
