### PR TITLE
Add paginator helper

### PR DESCRIPTION
**Pull request by tmaier**
Unfinished and untested. Just to get the ball rolling.
Comments and suggestions are highly welcome.

* [x] Allow to set some options
* [x] Checks if order attribute is an accepted range
* [x] Take into account when `options[:end] > count`
* [x] Get data from request header
* [x] Parse request header
* [x] Allow to set order
* [x] Add tests
* [x] must set start and end later --> pagination with block

# How to use

In your Endpoint:

## If you want to return uuids in the Range header

```
Content-Range: id 01234567-89ab-cdef-0123-456789abcdef..01234567-89ab-cdef-0123-456789abcdef/400; max=200
```

Use `uuid_paginator` helper

## If numbering the items is enough

```
Content-Range: id 0..199/400; max=200
```

```ruby
paginator = integer_paginator(User.count)
query =
  User.order(paginator[:order_by])
    .limit(paginator[:limit])
    .offset(paginator[:offset])
```

Heroku documentation on ranges: https://devcenter.heroku.com/articles/platform-api-reference#ranges

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
@brandur ... you promised...

**Comment by brandur** [comment]
I'm a horrible person :/

@uhoh-itsmaciek Do you need one of these or were you just looking at open pulls?

**Comment by uhoh-itsmaciek** [comment]
The latter. I was browsing PRs after opening #146 and thought this seemed neat. But we're all horrible people; I'm just giving you a hard time.

It would be cool to see this in though. Let me know if I can help.

**Comment by DyegoCosta** [comment]
+1
I'd love to see this in

**Comment by tmaier** [comment]
Closing this in favor for #234. Hope that pagination support will land soon :)

**Comment by gudmundur** [comment]
@tmaier I've been waiting for any kind of pagination to land. Still waiting for some of the details to settle on the other PR before going ahead.

**Pull request closed without merging**
