### PR TITLE
Make rack-timeout a dependency of the template app

### PR DESCRIPTION
**Pull request by pedro**
Just makes more sense, pliny doesnt need it internally

### CODE REVIEW

**Comment by dmathieu** [comment]
Meaning we can also remove (bad idea) or use another version. Good idea. :+1:

**Comment by brandur** [comment]
Definitely a good call. +1.

**Comment by pedro** [comment]
Cool, released in 0.14. /cc @gudmundur I think you were waiting for the `DB` changes so they're out too! next up we need to get you to release :}

**Comment by gudmundur** [comment]
Thanks @pedro. I was planning on doing a release with the `DB` changes, but no need now! :dancer:

**Pull request merged**
