### PR TITLE
Use the current ruby version when generating a new project

### PR DESCRIPTION
**Pull request by dmathieu**

### CODE REVIEW

**Comment by brandur** [comment]
Seems like an improvement! It does have a slight disadvantage in that if the local creator's Ruby version is outdated, then the new Pliny project will also be created on that outdated version of Ruby.

**Comment by dmathieu** [comment]
It does have that disadvantage, yet.
For the record, rails [does the same thimg](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L4).

**Comment by brandur** [comment]
> For the record, rails does the same thimg.

Ah, fair enough.

**Comment by gudmundur** [comment]
> Seems like an improvement! It does have a slight disadvantage in that if the local creator's Ruby version is outdated, then the new Pliny project will also be created on that outdated version of Ruby.

I'm assuming this can be checked in code before generating? I.e. if Ruby version is older than what we require, warn or err?

**Comment by gudmundur** [comment]
@dmathieu 2.4.0 sounds about right.

**Comment by dmathieu** [comment]
I've updated the PR to do just that.

**Comment by dmathieu** [comment]
Sorry, I didn't see the tests were failing. I've fixed them, the last failing one seems to be an unrelated issue.

**Pull request closed without merging**
