### PR TITLE
log request id

### PR DESCRIPTION
**Pull request by csquared**

### CODE REVIEW

**Comment by gudmundur** [comment]
I believe this PR can be closed as this has [already landed in a middleware](https://github.com/interagent/pliny/blob/6c8c968cff894607a637be1e4187f55538dc6b2d/lib/pliny/middleware/instruments.rb).

**Comment by brandur** [comment]
+1! Closing this out for now. Thanks for following up @gudmundur.

**Comment by mattreduce** [comment]
@brandur the PR is still open, by the way :grin:

**Comment by brandur** [comment]
Oops. @mattreduce Thanks :)

**Pull request closed without merging**
